# -*- coding: utf-8 -*-

"""
env_plane_dispatcher.py - Dispatch events generated by the environment plane
model
"""



class EnvPlaneDispatcher(object):
    def __init__(self, controller, opensand_view):
        self._event_notebook = None
        self._controller = controller
        self._opensand_view = opensand_view
        
        controller.set_observer(self)

    
    def program_list_changed(self):
        if not self._opensand_view:
            return
    
        programs = {}
        for program in self._controller.get_programs():
            programs[program.ident] = program
        
        self._opensand_view.on_program_list_changed(programs)
    
    def new_probe_value(self, probe, time, value):
        return
    
    def new_event(self, program, name, level, message):
        if not self._opensand_view:
            return
    
        self._opensand_view.on_new_program_event(program, name, level, message)
    