#!/bin/sh
set -e

case "$1" in
  remove|remove-in-favour|deconfigure|deconfigure-in-favour)
    if [ -f /etc/systemd/system/opensand-conf.service ]; then
      systemctl disable opensand-conf || exit $?
      systemctl stop opensand-conf || exit $?
    fi
    ;;

  upgrade|failed-upgrade)
    ;;

  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac



exit 0

