#!/bin/bash

MODULES='all libs core services lan encap'
USEROPTS=""

# Get list of all supported distributions
THIS_DIR="$(readlink -e $0)"
THIS_DIR="$(dirname ${THIS_DIR})"
DISTS=$(find $THIS_DIR -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)
DISTS=$(echo $DISTS | tr -d '\n')

usage()
{
    echo 'Usage : build-pkgs [OPTIONS] -s <src path> -d <dst path> -t <dist> TARGET'
    echo 'Available TARGETS :   all:      build all packages (default)'
    echo '                      libs:     build only libraries packages'
    echo '                      core:     build only core packages'
    echo '                      services: build only services packages'
    echo '                      encap:    build only encapsulation plugins'
    echo '                      lan:      build only lan adaptation plugins'
    echo 'Available OPTIONS :   -m        move packages into manager, daemon and all'
    echo '                                directories.'
    echo '                      -i        install build-dependencies automatically'
    echo '                      -f        add a user flag to packages'
    echo 'List of available distributions:'
    echo $DISTS
    exit 1
}

make_libs()
{
    echo "Building OpenSAND libraries for $TARGET_DIST"
    # Package and install opensand-output
    $THIS_DIR/$TARGET_DIST/build-pkg $USEROPTS -s $SRC_DIR -d $DST_DIR $INSTALL_DEP -i opensand-output || error
    # Package and install opensand-conf
    $THIS_DIR/$TARGET_DIST/build-pkg $USEROPTS -s $SRC_DIR -d $DST_DIR $INSTALL_DEP -i opensand-conf || error
    # Package and install opensand-rt
    $THIS_DIR/$TARGET_DIST/build-pkg $USEROPTS -s $SRC_DIR -d $DST_DIR $INSTALL_DEP -i opensand-rt || error
    echo "Finished building OpenSAND libraries for $TARGET_DIST"
}

make_core()
{
    echo "Building OpenSAND core for $TARGET_DIST"
    # Package and install opensand-core
    $THIS_DIR/$TARGET_DIST/build-pkg $USEROPTS -s $SRC_DIR -d $DST_DIR $INSTALL_DEP -i opensand-core
    echo "Finished building OpenSAND core for $TARGET_DIST"
}

make_services()
{
    echo "Building OpenSAND services for $TARGET_DIST"
    # Package and install opensand-collector
    $THIS_DIR/$TARGET_DIST/build-pkg $USEROPTS -s $SRC_DIR -d $DST_DIR $INSTALL_DEP opensand-collector 
    # Package and install opensand-daemon
    $THIS_DIR/$TARGET_DIST/build-pkg $USEROPTS -s $SRC_DIR -d $DST_DIR $INSTALL_DEP opensand-daemon 
    # Package and install opensand-manager
    $THIS_DIR/$TARGET_DIST/build-pkg $USEROPTS -s $SRC_DIR -d $DST_DIR $INSTALL_DEP opensand-manager
    # Package and install opensand-meta
    $THIS_DIR/$TARGET_DIST/build-pkg $USEROPTS -s $SRC_DIR -d $DST_DIR $INSTALL_DEP opensand-meta
    echo "Finished building OpenSAND services for $TARGET_DIST"
}

make_encap()
{
    echo "Building OpenSAND encapsulation plugins for $TARGET_DIST"
    # Package and install opensand-plugins/encapsulation/gse
    $THIS_DIR/$TARGET_DIST/build-pkg $USEROPTS -s $SRC_DIR -d $DST_DIR $INSTALL_DEP opensand-plugins/encapsulation/gse
    $THIS_DIR/$TARGET_DIST/build-pkg $USEROPTS -s $SRC_DIR -d $DST_DIR $INSTALL_DEP opensand-plugins/encapsulation/rle
    echo "Finished building OpenSAND encapsulation plugins for $TARGET_DIST"
}

make_lan()
{
    echo "Building OpenSAND LAN adaptation plugins for $TARGET_DIST"
    # Package and install opensand-plugins/encapsulation/gse
    $THIS_DIR/$TARGET_DIST/build-pkg $USEROPTS -s $SRC_DIR -d $DST_DIR $INSTALL_DEP opensand-plugins/lan_adaptation/rohc
    echo "Finished building OpenSAND LAN adaptation plugins for $TARGET_DIST"
}

error()
{
    exit 1
}

success()
{
    echo "done."
}

clean()
{
    # Delete any remaining .deb or any files remaining from last packaging
    rm -rf $DST_DIR/src/*
    rm -rf $DST_DIR/pkgs/*
}

move()
{
    # Create dirs if they don't exist
    mkdir -p $DST_DIR/pkgs/manager
    mkdir -p $DST_DIR/pkgs/daemon
    mkdir -p $DST_DIR/pkgs/all

    # Copy packages for daemon
    cp $DST_DIR/pkgs/libopensand-conf_*.deb \
       $DST_DIR/pkgs/libopensand-plugin_*.deb \
       $DST_DIR/pkgs/libopensand-output_*.deb \
       $DST_DIR/pkgs/libopensand-rt_*.deb \
       $DST_DIR/pkgs/opensand-core-bin_*.deb \
       $DST_DIR/pkgs/opensand-daemon_*.deb \
       $DST_DIR/pkgs/libopensand-*plugin_*.deb \
       $DST_DIR/pkgs/opensand_*.deb \
       $DST_DIR/pkgs/daemon >/dev/null 2>&1 
    echo 'Daemon packages copied to '$DST_DIR'/pkgs/daemon'
    # Copy packages for manager
    cp $DST_DIR/pkgs/libopensand-conf_*.deb \
       $DST_DIR/pkgs/libopensand-plugin_*.deb  \
       $DST_DIR/pkgs/libopensand-output_*.deb \
       $DST_DIR/pkgs/libopensand-rt_*.deb \
       $DST_DIR/pkgs/opensand-core-*_*.deb \
       $DST_DIR/pkgs/opensand-daemon_*.deb \
       $DST_DIR/pkgs/libopensand-*plugin_*.deb \
       $DST_DIR/pkgs/opensand-manager*.deb \
       $DST_DIR/pkgs/libopensand-*plugin-manager*.deb  \
       $DST_DIR/pkgs/opensand-collector_*.deb \
       $DST_DIR/pkgs/opensand_*.deb \
       $DST_DIR/pkgs/manager >/dev/null 2>&1
    echo 'Manager packages copied to '$DST_DIR'/pkgs/manager'
    # Move all packages to all
    mv $DST_DIR/pkgs/*.deb $DST_DIR/pkgs/all >/dev/null  2>&1
    echo 'All packages moved to '$DST_DIR'/pkgs/all'

}

while getopts ":s:d:t:himf:" o; do
    case "${o}" in
        s)
            SRC_DIR=$(readlink -f $OPTARG)
            ;;
        d)
            DST_DIR=$(readlink -f $OPTARG)
            ;;
        t)
            TARGET_DIST=$OPTARG
            ;;
        m)
            MOVE_PKG=true
            ;;
        i)
            INSTALL_DEP="-I"
            ;;
        f)
            if [ -z $OPTARG ]
            then
                echo "No user flag set!" && usage
            fi
            USEROPTS="$USEROPTS -f $OPTARG"
            ;;
        h)
            usage
            ;;
        *)
            if [ -z $OPTARG ]
            then
                echo "Invalid option \"${o}\"!"
            else
                echo "Invalid option \"${o} $OPTARG\"!"
            fi
            usage
            ;;
    esac
done
shift $((OPTIND-1))

# Make sure the script is run as root
if [ "$(id -u)" != "0" ];
then
    echo "This script must be run as root" 1>&2
    exit 1
fi

MODULE=$1

if [ -z $MODULE ];
then
    MODULE='all'
fi

# Show usage if module is not a valid option
if [[ ! " $MODULES " =~ " $MODULE " ]]
then
    echo "Invalid module!" && usage
fi

# Show usage if distribution is not a valid option
if [[ ! " $DISTS " =~ " $TARGET_DIST " ]]
then
    echo "Invalid distribution!" && usage
fi

# Check if valid source dir
if [ ! -d "$SRC_DIR" ]
then
    echo "Invalid source dir $SRC_DIR" && usage
fi

# Create dirs if they don't exist. Empty if they do.
mkdir -p $DST_DIR/src
mkdir -p $DST_DIR/pkgs
clean

case $MODULE in
    "all")
        make_libs
        make_core
        make_services
        make_encap
        make_lan
        ;;
    "libs")
        make_libs
        ;;
    "core")
        make_core
        ;;
    "services")
        make_services
        ;;
    "encap")
        make_encap
        ;;
    "lan")
        make_lan
        ;;
    *)
        ;;
esac

echo 'Finished packaging.'

if [ -v "MOVE_PKG" ];
then
    move
fi
