/*
 *
 * OpenSAND is an emulation testbed aiming to represent in a cost effective way a
 * satellite telecommunication system for research and engineering activities.
 *
 *
 * Copyright © 2013 TAS
 *
 *
 * This file is part of the OpenSAND testbed.
 *
 *
 * OpenSAND is free software : you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see http://www.gnu.org/licenses/.
 *
 */

/**
 * @file Event.h
 * @brief The Event class represent an event generated by the application.
 * @author Vincent Duvert <vduvert@toulouse.viveris.com>
 */


#ifndef _EVENT_H
#define _EVENT_H

#include <string>
#include <stdint.h>

/**
 * @brief Event severity levels
 **/
enum event_level_t
{
	LEVEL_DEBUG,   /*!< Debug level */
	LEVEL_INFO,    /*!< Information level */
	LEVEL_WARNING, /*!< Warning level */
	LEVEL_ERROR    /*!< Error level */
};

/**
 * @class Represent an event
 */
class Event
{
	friend class OutputInternal;

protected:
	Event(uint8_t id, const std::string &identifier,
	      event_level_t level);
	virtual ~Event();

private:
	/// the event ID
	uint8_t id;
	/// the event identifier
	std::string identifier;
	/// the event level
	event_level_t level;
};

#endif
