/*
 *
 * OpenSAND is an emulation testbed aiming to represent in a cost effective way a
 * satellite telecommunication system for research and engineering activities.
 *
 *
 * Copyright © 2020 TAS
 *
 *
 * This file is part of the OpenSAND testbed.
 *
 *
 * OpenSAND is free software : you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see http://www.gnu.org/licenses/.
 *
 */

/**
 * @file OutputEvent.cpp
 * @brief The OutputEvent class represent an event generated by the application.
 *        This is a specific log that should always be sent to manager
 *        if collector is enabled, it is used to describe important
 *        steps in platform behaviour
 * @author Vincent Duvert     <vduvert@toulouse.viveris.com>
 * @author Mathias Ettinger   <mathias.ettinger@viveris.fr>
 */


#include "OutputEvent.h"


OutputEvent::OutputEvent(const std::string& name) : OutputLog(LEVEL_EVENT, name)
{
}


OutputEvent::~OutputEvent()
{
}


void OutputEvent::setDisplayLevel(log_level_t)
{
}


void OutputEvent::sendEvent(const char* msg_format, ...) const
{
  std::va_list args;
  va_start(args, msg_format);
  vSendLog(LEVEL_EVENT, msg_format, args);
  va_end(args);
}
