#!/bin/bash

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage()
{
    echo 'Usage : $0 -s /path/to/sources -d /path/to/build'
}

while getopts ":s:d:h" o; do
    case "${o}" in
        s)
            SRC_DIR=`echo $OPTARG | sed 's/\/$//'`
            ;;
        d)
            DST_DIR=`echo $OPTARG | sed 's/\/$//'`
            ;;
        h)
            usage
            exit 0
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done
shift $((OPTIND-1))

# Make sure the script is run as root
if [ "$(id -u)" != "0" ];
then
    echo "This script must be run as root" 1>&2
    exit 1
fi

# Check if valid source dir
if [ ! -d "$SRC_DIR" ]
then
    echo "Invalid source dir \"$SRC_DIR\"" && usage
fi

# Check if valid destination dir
if [ ! -d "$DST_DIR" ]
then
    echo "Invalid destination dir \"$DST_DIR\"" && usage
fi

# Create symbolic link to service file
cd $THIS_DIR
ln -s ../init/opensand-collector.service $DST_DIR/debian/opensand-collector.service
