#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule


ST_LIST="1, 3, 4, 5"
WS_LIST="1, 2, 3, 4, 5"
SAT_EMU_IP4ADDR="192.168.18.15/24"
SAT_EMU_IP6ADDR="2001:660:6602:101::15/64"
GW_EMU_IP4ADDR="192.168.18.2/24"
GW_IP4ADDR="192.168.20.1/24"
GW_EMU_IP6ADDR="2001:660:6602:101::2/64"
GW_IP6ADDR="2001:660:6602:103::1/64"
CONFIG_LEVEL="ADVANCED"
DHCP="false"

RECONFIG="false"

usage(){
    /bin/echo -e "Usage: $0 command\n\twith command: configure or reconfigure"
}

configure(){
    db_beginblock
    db_input high platine-daemon/service/type || true
    db_go
    db_input high platine-daemon/service/name || true
    db_go
    db_get platine-daemon/service/name
    NAME=$RET
    if [ "$NAME" = "ST" ]; then
        db_subst platine-daemon/service/st_instance inst_list ${ST_LIST}
        db_input high platine-daemon/service/st_instance || true
        db_go
        db_get platine-daemon/service/st_instance
        INST=$RET
    fi
    if [ "$NAME" = "GW" ]; then
        db_set platine-daemon/service/st_instance 0
    fi
    if [ "$NAME" = "WS" ]; then
        # enable WS2
        db_subst platine-daemon/service/st_instance inst_list ${WS_LIST}
        db_input high platine-daemon/service/st_instance || true
        db_go
        db_get platine-daemon/service/st_instance
        INST=$RET
        db_input high platine-daemon/service/ws_instance || true
        db_go
    fi
    db_input low platine-daemon/service/port || true
    db_go
    db_endblock
    db_beginblock
    db_input low platine-daemon/command/port || true
    db_go
    db_endblock
    db_beginblock
    db_input low platine-daemon/state/port || true
    db_go
    db_endblock
    db_beginblock
    db_input high platine-daemon/network/config_level || true
    db_go
    db_get platine-daemon/network/config_level
    CONFIG_LEVEL=$RET
	#TODO for ST also
    if [ "$NAME" = "WS" ]; then
        db_input high platine-daemon/network/dhcp || true
        db_go
        db_get platine-daemon/network/dhcp
        DHCP=$RET
    fi
    set_ifaces
    db_endblock
}

set_ifaces(){
    if [ "$CONFIG_LEVEL" != "AUTOMATIC" ]; then
        if [ "$NAME" != "WS" ]; then
            db_input high platine-daemon/network/emu_iface || true
            db_go
            if [ "$RECONFIG" = "false" ]; then
                if [ "$NAME" = "SAT" ]; then
                    db_set platine-daemon/network/emu_ipv4 ${SAT_EMU_IP4ADDR}
                    db_set platine-daemon/network/emu_ipv6 ${SAT_EMU_IP6ADDR}
                elif [ "$NAME" = "GW" ]; then
                    db_set platine-daemon/network/emu_ipv4 ${GW_EMU_IP4ADDR}
                    db_set platine-daemon/network/emu_ipv6 ${GW_EMU_IP6ADDR}
                elif [ "$NAME" = "ST" ]; then
                    db_set platine-daemon/network/emu_ipv4 "192.168.18.${INST}/24"
                    db_set platine-daemon/network/emu_ipv6 "2001:660:6602:101::${INST}/24"
                fi
            fi
            db_input high platine-daemon/network/emu_ipv4 || true
            db_go
            db_input high platine-daemon/network/emu_ipv6 || true
            db_go
        fi
        if [ "$NAME" != "SAT" ] && [ "$NAME" != "WS" -o "$DHCP" = "false" ]; then
            add=1
            if [ "$NAME" = "WS" ]; then
                # use a random value to limit WS with the same address
                # ST physical interface has address .1 and tun interface
                # (platine) has address .2
                add=`od -An -N1 -tu1 /dev/urandom`
                add=$((add % 253))
                add=$((add + 3))
            fi
            db_input high platine-daemon/network/lan_iface || true
            db_go
            if [ "$RECONFIG" = "false" ]; then
                if [ "$NAME" != "GW" ]; then
                    net=$((18+$INST))
                    db_set platine-daemon/network/lan_ipv4 "192.168.${net}.${add}/24"
                    net=$((101+$INST))
                    db_set platine-daemon/network/lan_ipv6 "2001:660:6602:${net}::${add}/24"
                else
                    db_set platine-daemon/network/lan_ipv4 ${GW_IP4ADDR}
                    db_set platine-daemon/network/lan_ipv6 ${GW_IP6ADDR}
                fi
            fi
            db_input high platine-daemon/network/lan_ipv4 || true
            db_go
            db_input high platine-daemon/network/lan_ipv6 || true
            db_go
        fi
    else
        if [ "$NAME" != "WS" ]; then
            db_input high platine-daemon/network/emu_iface || true
            db_go
        fi
        if [ "$NAME" != "SAT" ] && [ "$NAME" != "WS" -o "$DHCP" != "false" ]; then
            db_input high platine-daemon/network/lan_iface || true
            db_go
        fi
    fi
}

reset(){
    db_reset platine-daemon/service/name
    db_reset platine-daemon/service/type
    db_reset platine-daemon/service/st_instance
    db_reset platine-daemon/service/ws_instance
    db_reset platine-daemon/service/port
    db_reset platine-daemon/command/port
    db_reset platine-daemon/state/port
    db_reset platine-daemon/network/config_level
    db_reset platine-daemon/network/dhcp
    db_reset platine-daemon/network/emu_iface
    db_reset platine-daemon/network/emu_ipv4
    db_reset platine-daemon/network/emu_ipv6
    db_reset platine-daemon/network/lan_iface
    db_reset platine-daemon/network/lan_ipv4
    db_reset platine-daemon/network/lan_ipv6
}

unseen(){
    db_fset platine-daemon/service/name seen false
    db_fset platine-daemon/service/type seen false
    db_fset platine-daemon/service/st_instance seen false
    db_fset platine-daemon/service/ws_instance seen false
    db_fset platine-daemon/service/port seen false
    db_fset platine-daemon/command/port seen false
    db_fset platine-daemon/state/port seen false
    db_fset platine-daemon/network/config_level seen false
    db_fset platine-daemon/network/dhcp seen false
    db_fset platine-daemon/network/emu_iface seen false
    db_fset platine-daemon/network/emu_ipv4 seen false
    db_fset platine-daemon/network/emu_ipv6 seen false
    db_fset platine-daemon/network/lan_iface seen false
    db_fset platine-daemon/network/lan_ipv4 seen false
    db_fset platine-daemon/network/lan_ipv6 seen false
}

if [ "$#" -gt 0 ]; then
    if [ "$1" = "configure" ]; then
        db_fget platine-daemon/default seen
        if [ "$RET" = "false" ]; then
            db_input high platine-daemon/default || true
            db_go
            db_get platine-daemon/default
            if [ "$RET" = "true" ]; then
                reset
                db_stop
            else
                configure
            fi
        else
            RECONFIG="true"
            configure
        fi
    elif [ "$1" = "reconfigure" ]; then
        RECONFIG="true"
        unseen
        configure
    else
        usage
        exit 1
    fi
else
    usage
fi


