#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

IFACES_LIST=$(ip a | sed -rn "s/^[0-9]+: ([^:]+): .*/\1/p" | paste -d',' -s)
IFACES_LIST=$(echo ${IFACES_LIST} | sed 's/opensand_tun//')
IFACES_LIST=$(echo ${IFACES_LIST} | sed 's/opensand_tap//')
IFACES_LIST=$(echo ${IFACES_LIST} | sed 's/opensand_br//')
IFACES_LIST=$(echo ${IFACES_LIST} | sed 's/,\+/,/g' | sed 's/^,//' | sed 's/,$//')
IFACES_LIST=$(echo ${IFACES_LIST} | sed 's/,/,\ /g')

usage(){
    /bin/echo -e "Usage: $0 command\n\twith command: configure or reconfigure"
}

configure(){
    STATE=1
    while true; do
        case "$STATE" in
        1)
            db_beginblock
            db_input high opensand-collector/service/type || true
        ;;
        2)
            db_subst opensand-collector/service/interface ifaces_list "${IFACES_LIST}"
            db_input high opensand-collector/service/interface || true
            db_endblock
        ;;
        *)
            # The default case catches when $STATE is greater than the
            # last implemented state, and breaks out of the loop. This
            # requires that states be numbered consecutively from 1
            # with no gaps, as the default case will also be entered
            # if there is a break in the numbering
            break # exits the enclosing "while" loop
        ;;
        esac

        if db_go; then
            STATE=$(($STATE + 1))
        else
            STATE=$(($STATE - 1))
        fi
    done

    if [ $STATE -eq 0 ]; then
        # The user has asked to back up from the first
        # question. This case is problematical. Regular
        # dpkg and apt package installation isn’t capable
        # of backing up questions between packages as this
        # is written, so this will exit leaving the package
        # unconfigured - probably the best way to handle
        # the situation.
        exit 10
    fi
}

unseen(){
    db_fset opensand-collector/service/type seen false
    db_fset opensand-collector/service/interface seen false
}

db_capb backup

if [ "$#" -gt 0 ]; then
    if [ "$1" = "configure" ]; then
        configure
    elif [ "$1" = "reconfigure" ]; then
        unseen
        configure
    else
        usage
        exit 1
    fi
else
    usage
fi

exit 0
