#!/bin/bash

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage()
{
    echo 'Usage : $0 -s /path/to/sources -d /path/to/build'
}

while getopts ":s:d:h" o; do
    case "${o}" in
        s)
            SRC_DIR=`echo $OPTARG | sed 's/\/$//'`
            ;;
        d)
            DST_DIR=`echo $OPTARG | sed 's/\/$//'`
            ;;
        h)
            usage
            exit 0
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done
shift $((OPTIND-1))

# Check if valid source dir
if [ ! -d "$SRC_DIR" ]
then
    echo "Invalid source dir \"$SRC_DIR\"" && usage
fi

# Check if valid destination dir
if [ ! -d "$DST_DIR" ]
then
    echo "Invalid destination dir \"$DST_DIR\"" && usage
fi

# Create symbolic link to init file
cd $THIS_DIR
ln -s ../init/opensand-collector $DST_DIR/debian/opensand-collector.init
