#ifndef	Probe_e
#   define	Probe_e

/* SYSTEM RESOURCES */
/* PROJECT RESOURCES */
#   include "Types_e.h"

typedef enum
{
	C_PROBE_ST_TERMINAL_QUEUE_SIZE = 1,
	C_PROBE_ST_PHYSICAL_OUTGOING_THROUGHPUT,
	C_PROBE_ST_RBDC_REQUEST_SIZE,
	C_PROBE_ST_VBDC_REQUEST_SIZE,
	C_PROBE_ST_ALLOCATION_SIZE,
	C_PROBE_ST_UNUSED_CAPACITY,
	C_PROBE_ST_REAL_INCOMING_THROUGHPUT,
	C_PROBE_ST_REAL_OUTGOING_THROUGHPUT,
	C_PROBE_ST_CRA,
	C_PROBE_ST_OUTPUT_HDLB_RATE,
	C_PROBE_ST_OUTPUT_HDLB_DROPS,
	C_PROBE_ST_OUTPUT_HDLB_BACKLOG,
	C_PROBE_ST_BBFRAME_DROPED_RATE,
	C_PROBE_ST_REAL_MODCOD,
	C_PROBE_ST_USED_MODCOD
} T_PROBE_ST_ID;

/* Probe ID for GW : Do not use it directly but use macros defined below*/
typedef enum
{
	C_PROBE_GW_RBDC_REQUEST_NUMBER = 1,
	C_PROBE_GW_RBDC_REQUESTED_CAPACITY,
	C_PROBE_GW_VBDC_REQUEST_NUMBER,
	C_PROBE_GW_VBDC_REQUESTED_CAPACITY,
	C_PROBE_GW_UPLINK_FAIR_SHARE,
	C_PROBE_GW_CRA_ALLOCATION,
	C_PROBE_GW_CRA_ST_ALLOCATION,
	C_PROBE_GW_RBDC_ALLOCATION,
	C_PROBE_GW_RBDC_ST_ALLOCATION,
	C_PROBE_GW_RBDC_MAX_ALLOCATION,
	C_PROBE_GW_RBDC_MAX_ST_ALLOCATION,
	C_PROBE_GW_VBDC_ALLOCATION,
	C_PROBE_GW_FCA_ALLOCATION,
	C_PROBE_GW_LOGGED_ST_NUMBER,
	C_PROBE_GW_BBFRAME_SENT_PER_FRAME,
} T_PROBE_GW_ID;



#endif
