/*
 *
 * OpenSAND is an emulation testbed aiming to represent in a cost effective way a
 * satellite telecommunication system for research and engineering activities.
 *
 *
 * Copyright © 2012 CNES
 *
 *
 * This file is part of the OpenSAND testbed.
 *
 *
 * OpenSAND is free software : you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see http://www.gnu.org/licenses/.
 *
 */

/**
 * @file Event.h
 * @brief The Event class represent an event generated by the application.
 */


#ifndef _EVENT_H
#define _EVENT_H

#include <stdint.h>

enum event_level {
	LEVEL_DEBUG,
	LEVEL_INFO,
	LEVEL_WARNING,
	LEVEL_ERROR
};

class Event
{
	friend class EnvPlaneInternal;

	inline const char* identifier() const { return this->_identifier; };
	inline event_level level() const { return this->_level; };

protected:
	Event(uint8_t id, const char* identifier, event_level level);
	virtual ~Event();

private:
	uint8_t id;
	char* _identifier;
	event_level _level;
};

#endif
