#!/bin/sh
set -e

case "$1" in
  abort-upgrade|abort-remove|abort-deconfigure|configure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac


if [ -f /etc/systemd/system/opensand-conf.service ]; then
  systemctl daemon-reload
  systemctl enable opensand-conf.service
  systemctl restart opensand-conf.service
fi



exit 0

