#!/bin/bash
### BEGIN INIT INFO
# Provides:          opensand-network
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Startup script for the OpenSAND network
# Description:       This script configure the network interfaces for OpenSAND
#                    according to the type of host
### END INIT INFO
# -*- coding: utf-8 -*-
# Debian init.d script for OpenSAND Network
# Written by Julien BERNARD <jbernard@toulouse.viveris.com>

SCRIPT_NAME="$0"
LOCK_NAME="opensand-network"
LOGGER="/usr/bin/logger"
CONFSCRIPT="/usr/libexec/opensand/write_initialize_config"
RESETSCRIPT="/usr/libexec/opensand/remove_config"

. /lib/lsb/init-functions


# Start the server
start()
{
    log_daemon_msg "Configuring the OpenSAND network"

    # Check that executable is present
    if [ ! -x ${CONFSCRIPT} ] ; then
        log_failure_msg "OpenSAND daemon script '${CONFSCRIPT}' not found on system"
        log_end_msg 1
        exit 1
    fi

    # Start the OpenSAND network
    start-stop-daemon --start --exec ${CONFSCRIPT} 1>/dev/null
    if [ $? -ne 0 ] ; then
        log_failure_msg "failed to configure the OpenSAND network"
        log_end_msg 1
        exit 1
    fi

    # everything went fine
    log_end_msg 0
    touch /var/lock/${LOCK_NAME}
}


# Stop the OpenSAND network
stop()
{
    log_daemon_msg "Removing configuration for the OpenSAND network"

    # Check that executable is present
    if [ ! -x ${RESETSCRIPT} ] ; then
        log_failure_msg "opensand-daemon binary '${RESETSCRIPT}' not found on system"
        log_end_msg 1
        exit 1
    fi

    # Start the reset script
    start-stop-daemon --start --exec ${RESETSCRIPT} 1>/dev/null
    if [ $? -ne 0 ] ; then
        log_failure_msg "failed to remove configuration of the OpenSAND Network"
        log_end_msg 1
        exit 1
    fi

    log_end_msg 0
    rm -f /var/lock/${LOCK_NAME}
}


# Stop then start the server
restart()
{
    stop
    sleep 2
    start || exit 1
}


# Which action to perform?
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    condrestart)
        [ -e /var/lock/${LOCK_NAME} ] && restart
        ;;
    status)
        if [ -e /var/lock/${LOCK_NAME} ]; then
            log_success_msg "The OpenSAND network is configured."
        else
            log_failure_msg "The OpenSAND network is not configured."
            exit 1
        fi
        ;;
    *)
        echo "Usage $0 {start|stop|restart|condrestart|status}"
esac

exit 0


