#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule


ST_LIST="1, 2, 3, 4, 5"
GW_LIST="0, 6"
WS_LIST="0, 1, 2, 3, 4, 5, 6"
SAT_EMU_IP4ADDR="192.168.18.15/24"
SAT_EMU_IP6ADDR="2001:660:6602:101::15/64"
GW_NET=42
GW_EMU_IP4ADDR="192.168.18.$GW_NET/24"
GW_IP4ADDR="192.168.$GW_NET.1/24"
GW_IP6ADDR="2001:660:6602:1$GW_NET::1/64"
CONFIG_LEVEL="ADVANCED"
DHCP="false"
ST_INST_DESCR="Select the ID of the satellite terminal"
GW_INST_DESCR="Select the ID of the gateway used to identify the it when in multi-GW"
GW_TYPE_DESCR="Select the type of GW"
GW_TYPE_LIST="GW, GW-NET-ACC, GW-PHY"
GW_TYPE_DEFAULT="GW"
NAME_ADV="false"

RECONFIG="false"

usage(){
    /bin/echo -e "Usage: $0 command\n\twith command: configure or reconfigure"
}

configure(){
    STATE=1
    while true; do
        case "$STATE" in
        1)
            db_beginblock
            db_input high opensand-daemon/service/type || true
        ;;
        2)
            db_input high opensand-daemon/service/name || true
            db_endblock
        ;;
        3)
            db_beginblock
            NAME_ADV="false"
            db_get opensand-daemon/service/name
            NAME=$RET
            if [ "$NAME" = "GW" ]; then
                db_subst opensand-daemon/service/name_adv name_adv_list ${GW_TYPE_LIST}
                db_subst opensand-daemon/service/name_adv name_adv_description ${GW_TYPE_DESCR}
                db_subst opensand-daemon/service/name_adv name_adv_default ${GW_TYPE_DEFAULT}
                db_input low opensand-daemon/service/name_adv || true
                NAME_ADV="true"
            else
                db_set opensand-daemon/service/name_adv $NAME
            fi
            db_endblock
        ;;
        4)
            db_beginblock
            db_get opensand-daemon/service/name_adv
            NAME=$RET

            if [ "$NAME" = "GW-PHY" ]; then
                db_subst opensand-daemon/interconnect/ip_remote ip_remote_desc "GW-NET-ACC"
                db_input low opensand-daemon/interconnect/ip_remote || true
            fi
            db_endblock
        ;;
        5)
            db_beginblock
            if [ "$NAME" = "GW-PHY" -o "$NAME" = "GW-NET-ACC" ]; then
                db_subst opensand-daemon/interconnect/port_upward port_upward_bottom "GW-PHY"
                db_subst opensand-daemon/interconnect/port_upward port_upward_top "GW-NET-ACC"
                db_input low opensand-daemon/interconnect/port_upward || true
            fi
            db_endblock
        ;;
        6)
            db_beginblock
            if [ "$NAME" = "GW-PHY" -o "$NAME" = "GW-NET-ACC" ]; then
                db_subst opensand-daemon/interconnect/port_downward port_downward_bottom "GW-PHY"
                db_subst opensand-daemon/interconnect/port_downward port_downward_top "GW-NET-ACC"
                db_input low opensand-daemon/interconnect/port_downward || true
            fi
            db_endblock
        ;;
        7)
            db_beginblock
            if [ "$NAME" = "ST" ]; then
                db_subst opensand-daemon/service/st_instance inst_list ${ST_LIST}
                db_subst opensand-daemon/service/st_instance inst_description ${ST_INST_DESCR}
                db_input high opensand-daemon/service/st_instance || true
            fi
            if [ "$NAME" = "GW" -o "$NAME" = "GW-PHY" -o "$NAME" = "GW-NET-ACC" ]; then
                db_subst opensand-daemon/service/st_instance inst_list ${GW_LIST}
                db_subst opensand-daemon/service/st_instance inst_description ${GW_INST_DESCR}
                db_input high opensand-daemon/service/st_instance || true
            fi
            if [ "$NAME" = "WS" ]; then
                # enable WS2
                db_subst opensand-daemon/service/st_instance inst_list ${WS_LIST}
                db_input high opensand-daemon/service/st_instance || true
            fi
        ;;
        8)
            if [ "$NAME" = "ST" ]; then
                db_get opensand-daemon/service/st_instance
                INST=$RET
            fi
            if [ "$NAME" = "GW" ]; then
                db_get opensand-daemon/service/st_instance
                INST=$RET
            fi
            if [ "$NAME" = "WS" ]; then
                db_get opensand-daemon/service/st_instance
                INST=$RET
                db_input high opensand-daemon/service/ws_instance || true
            fi
        ;;
        9)
            db_input high opensand-daemon/service/interface || true
            db_endblock
        ;;
        10)
            db_beginblock
            db_input low opensand-daemon/service/port || true
            db_endblock
        ;;
        11)
            db_beginblock
            db_input low opensand-daemon/command/port || true
            db_endblock
        ;;
        12)
            db_beginblock
            db_input low opensand-daemon/state/port || true
            db_endblock
        ;;
        13)
            db_beginblock
            db_input high opensand-daemon/network/config_level || true
        ;;
        14)
            db_get opensand-daemon/network/config_level
            CONFIG_LEVEL=$RET
            if [ "$NAME" != "SAT" -a "$NAME" != "GW-PHY" ]; then
                db_input high opensand-daemon/network/dhcp || true
            fi
        ;;
        15)
            if [ "$NAME" != "SAT" -a "$NAME" != "GW-PHY" ]; then
                db_get opensand-daemon/network/dhcp
                DHCP=$RET
                if [ "$NAME" != "WS" -a "$DHCP" = "true" ]; then
                    db_input high opensand-daemon/network/default_route || true
                fi
            fi
        ;;
        16)
            db_beginblock
            if [ "$CONFIG_LEVEL" != "AUTOMATIC" ]; then
                if [ "$NAME" != "WS"  -a "$NAME" != "GW-NET-ACC" ]; then
                    db_input high opensand-daemon/network/emu_iface || true
                    if [ "$RECONFIG" = "false" ]; then
                        if [ "$NAME" = "SAT" ]; then
                            db_set opensand-daemon/network/emu_ipv4 ${SAT_EMU_IP4ADDR}
                     
                        elif [ "$NAME" = "GW" -o "$NAME" = "GW-PHY" ]; then
                            if [ "${INST}" = "0" ]; then 
                                db_set opensand-daemon/network/emu_ipv4 ${GW_EMU_IP4ADDR}
                            else
                                db_set opensand-daemon/network/emu_ipv4 "192.168.18.${INST}/24"
                            fi
                    
                        elif [ "$NAME" = "ST" ]; then
                            db_set opensand-daemon/network/emu_ipv4 "192.168.18.${INST}/24"
                   
                        fi
                    fi
                    db_input high opensand-daemon/network/emu_ipv4 || true
                  
                fi
                if [ "$NAME" != "SAT" -a "$NAME" != "GW-PHY" ]; then
                    add=1
                    if [ "$NAME" = "WS" ]; then
                        db_input high opensand-daemon/network/ws_lan_iface || true
                        # use a random value to limit WS with the same address
                        # ST physical interface has address .1 and tun interface
                        # (opensand) has address .3
                        add=`od -An -N1 -tu1 /dev/urandom`
                        add=$((add % 252))
                        add=$((add + 4))
                    else
                        db_input high opensand-daemon/network/lan_iface || true
                    fi
                    if [ "$NAME" != "WS" -o "$DHCP" = "false" ]; then
                        if [ "$RECONFIG" = "false" ]; then
                            if [ "$NAME" != "GW" -a "$NAME" != "GW-NET-ACC" ]; then
                                net=$((18+$INST))
                                # WS behind GW
                                if [ "$INST" = "0" ]; then
                                    net="$GW_NET"
                                fi
                                if [ "$NAME" = "WS" ]; then
                                    db_set opensand-daemon/network/ws_lan_ipv4 "192.168.${net}.${add}/24"
                                else
                                    db_set opensand-daemon/network/lan_ipv4 "192.168.${net}.${add}/24"
                                fi
                                net=$((101+$INST))
                                # WS behind GW0
                                if [ "$INST" = "0" ]; then
                                    net="1$GW_NET"
                                fi
                                if [ "$NAME" = "WS" ]; then
                                    db_set opensand-daemon/network/ws_lan_ipv6 "2001:660:6602:${net}::${add}/64"
                                else
                                    db_set opensand-daemon/network/lan_ipv6 "2001:660:6602:${net}::${add}/64"
                                fi
                            else
                                if [ "${INST}" = "0" ]; then 
                                    db_set opensand-daemon/network/lan_ipv4 ${GW_IP4ADDR}
                                    db_set opensand-daemon/network/lan_ipv6 ${GW_IP6ADDR}
                                else
                                    net=$((18+$INST))
                                    db_set opensand-daemon/network/lan_ipv4 "192.168.${net}.${add}/24"
                                    net=$((101+$INST))
                                    db_set opensand-daemon/network/lan_ipv6 "2001:660:6602:${net}::${add}/64"
                                fi
                            fi
                        fi
                        if [ "$NAME" = "WS" ]; then
                            db_input high opensand-daemon/network/ws_lan_ipv4 || true
                            db_input high opensand-daemon/network/ws_lan_ipv6 || true
                        else
                            db_input high opensand-daemon/network/lan_ipv4 || true
                            db_input high opensand-daemon/network/lan_ipv6 || true
                            if [ "$NAME" = "ST" ]; then
                                db_input high opensand-daemon/network/lan_default_route || true
                            fi
                        fi
                    elif [ "$NAME" = "WS" -a "$DHCP" != "false" ]; then
                        net=$((101+$INST))
                        # WS behind GW
                        if [ "$INST" = "0" ]; then
                            net="1$GW_NET"
                        fi
                        db_set opensand-daemon/network/ws_lan_ipv6 "2001:660:6602:${net}::${add}/64"
                        db_input high opensand-daemon/network/ws_lan_ipv6 || true
                    fi
                fi
            else
                if [ "$NAME" != "WS" -a "$NAME" != "GW-NET-ACC" ]; then
                    db_input high opensand-daemon/network/emu_iface || true
                fi
                if [ "$NAME" != "SAT" -a "$NAME" != "GW-PHY" ] && 
                    [ "$NAME" != "WS" -o "$DHCP" != "false" ]; then
                    if [ "$NAME" = "WS" ]; then
                        db_input high opensand-daemon/network/ws_lan_iface || true
                    else
                        db_input high opensand-daemon/network/lan_iface || true
                    fi
                fi
            fi
            db_endblock
        ;;
        *)
            # The default case catches when $STATE is greater than the
            # last implemented state, and breaks out of the loop. This
            # requires that states be numbered consecutively from 1
            # with no gaps, as the default case will also be entered
            # if there is a break in the numbering
            break # exits the enclosing "while" loop
        ;;
        esac

        if db_go; then
            STATE=$(($STATE + 1))
        else
            STATE=$(($STATE - 1))
        fi
    done

    if [ $STATE -eq 0 ]; then
        # The user has asked to back up from the first
        # question. This case is problematical. Regular
        # dpkg and apt package installation isn’t capable
        # of backing up questions between packages as this
        # is written, so this will exit leaving the package
        # unconfigured - probably the best way to handle
        # the situation.
        exit 10
    fi
}

reset(){
    db_reset opensand-daemon/service/name
    db_reset opensand-daemon/service/name_adv
    db_reset opensand-daemon/service/type
    db_reset opensand-daemon/service/st_instance
    db_reset opensand-daemon/service/ws_instance
    db_reset opensand-daemon/service/interface
    db_reset opensand-daemon/service/port
    db_reset opensand-daemon/command/port
    db_reset opensand-daemon/state/port
    db_reset opensand-daemon/network/config_level
    db_reset opensand-daemon/network/dhcp
    db_reset opensand-daemon/network/default_route
    db_reset opensand-daemon/network/emu_iface
    db_reset opensand-daemon/network/emu_ipv4
    db_reset opensand-daemon/network/lan_iface
    db_reset opensand-daemon/network/lan_ipv4
    db_reset opensand-daemon/network/lan_ipv6
    db_reset opensand-daemon/network/lan_default_route
    db_reset opensand-daemon/network/ws_lan_iface
    db_reset opensand-daemon/network/ws_lan_ipv4
    db_reset opensand-daemon/network/ws_lan_ipv6
    db_reset opensand-daemon/interconnect/ip_remote
    db_reset opensand-daemon/interconnect/port_upward
    db_reset opensand-daemon/interconnect/port_downward
}

unseen(){
    db_fset opensand-daemon/service/name seen false
    db_fset opensand-daemon/service/name_adv seen false
    db_fset opensand-daemon/service/type seen false
    db_fset opensand-daemon/service/st_instance seen false
    db_fset opensand-daemon/service/ws_instance seen false
    db_fset opensand-daemon/service/interface seen false
    db_fset opensand-daemon/service/port seen false
    db_fset opensand-daemon/command/port seen false
    db_fset opensand-daemon/state/port seen false
    db_fset opensand-daemon/network/config_level seen false
    db_fset opensand-daemon/network/dhcp seen false
    db_fset opensand-daemon/network/default_route seen false
    db_fset opensand-daemon/network/emu_iface seen false
    db_fset opensand-daemon/network/emu_ipv4 seen false
    db_fset opensand-daemon/network/lan_iface seen false
    db_fset opensand-daemon/network/lan_ipv4 seen false
    db_fset opensand-daemon/network/lan_ipv6 seen false
    db_fset opensand-daemon/network/lan_default_route seen false
    db_fset opensand-daemon/network/ws_lan_iface seen false
    db_fset opensand-daemon/network/ws_lan_ipv4 seen false
    db_fset opensand-daemon/network/ws_lan_ipv6 seen false
    db_fset opensand-daemon/interconnect/ip_remote seen false
    db_fset opensand-daemon/interconnect/port_upward seen false
    db_fset opensand-daemon/interconnect/port_downward seen false
}

db_capb backup

if [ "$#" -gt 0 ]; then
    if [ "$1" = "configure" ]; then
        db_fget opensand-daemon/default seen
        if [ "$RET" = "false" ]; then
            db_input high opensand-daemon/default || true
            db_get opensand-daemon/default
            if [ "$RET" = "true" ]; then
                reset
                db_stop
            else
                configure
            fi
        else
            RECONFIG="true"
            configure
        fi
    elif [ "$1" = "reconfigure" ]; then
        RECONFIG="true"
        unseen
        configure
    else
        usage
        exit 1
    fi
else
    usage
fi

exit 0
