#!/bin/bash -e

# Source debconf library.
. /usr/share/debconf/confmodule


ST_LIST="1, 2, 3, 4, 5"
GW_LIST="0, 6"
WS_LIST="0, 1, 2, 3, 4, 5, 6"
SAT_EMU_IP4ADDR="192.168.18.15/24"
SAT_EMU_IP6ADDR="2001:660:6602:101::15/64"
GW_NET=42
GW_EMU_IP4ADDR="192.168.18.$GW_NET/24"
GW_IP4ADDR="192.168.$GW_NET.1/24"
GW_IP6ADDR="2001:660:6602:1$GW_NET::1/64"
CONFIG_LEVEL="ADVANCED"
DHCP="false"
ST_INST_DESCR="Select the ID of the satellite terminal"
GW_INST_DESCR="Select the ID of the gateway (if only one gateway in your topology, select 0)"
GW_TYPE_DESCR="Select the type of GW"
GW_TYPE_LIST="GW, GW-NET-ACC, GW-PHY"
GW_TYPE_DEFAULT="GW"
NAME_ADV="false"
IFACES_LIST=$(ip a | sed -rn "s/^[0-9]+: ([^:]+): .*/\1/p" | paste -d',' -s)
IFACES_LIST=$(echo ${IFACES_LIST} | sed 's/^lo,//' | sed 's/,lo$//' | sed 's/,lo,/,/')
IFACES_LIST=$(echo ${IFACES_LIST} | sed 's/opensand_tun//')
IFACES_LIST=$(echo ${IFACES_LIST} | sed 's/opensand_tap//')
IFACES_LIST=$(echo ${IFACES_LIST} | sed 's/opensand_br//')
IFACES_LIST=$(echo ${IFACES_LIST} | sed 's/,\+/,/g' | sed 's/^,//' | sed 's/,$//')
IFACES_LIST=$(echo ${IFACES_LIST} | sed 's/,/,\ /g')

usage(){
    /bin/echo -e "Usage: $0 command\n\twith command: configure or reconfigure"
}

configure(){
    STATE=1
    while true; do
        case "$STATE" in
        1)
            db_beginblock
            db_input high opensand-daemon/service/type || true
        ;;
        2)
            db_input high opensand-daemon/service/name || true
            db_endblock
        ;;
        3)
            db_beginblock
            NAME_ADV="false"
            db_get opensand-daemon/service/name
            NAME=$RET
            if [ "$NAME" = "GW" ]; then
                db_subst opensand-daemon/service/name_adv name_adv_list ${GW_TYPE_LIST}
                db_subst opensand-daemon/service/name_adv name_adv_description ${GW_TYPE_DESCR}
                db_subst opensand-daemon/service/name_adv name_adv_default ${GW_TYPE_DEFAULT}
                db_input low opensand-daemon/service/name_adv || true
                NAME_ADV="true"
            else
                db_set opensand-daemon/service/name_adv $NAME
            fi
            db_endblock
        ;;
        4)
            db_beginblock
            db_get opensand-daemon/service/name_adv
            NAME=$RET
            if [ "$NAME" = "GW-PHY" -o "$NAME" = "GW-NET-ACC" ]; then
                db_subst opensand-daemon/interconnect/interface ifaces_list "${IFACES_LIST}"
                db_input low opensand-daemon/interconnect/interface || true
            fi
            db_endblock
        ;;
        5)
            db_beginblock
            if [ "$NAME" = "GW-PHY" -o "$NAME" = "GW-NET-ACC" ]; then
                if [ "$NAME" = "GW-PHY" ]; then
                    RECOMMENDED_IP="192.168.17.1/24"
                elif [ "$NAME" = "GW-NET-ACC" ]; then
                    RECOMMENDED_IP="192.168.17.2/24"
                fi
                IPS_LIST=""
                db_get opensand-daemon/interconnect/interface_ip
                CURRENT_IP=${RET}
                if [ ! -z $CURRENT_IP ]; then
                    IPS_LIST="Current:${CURRENT_IP}, "
                fi
                IPS_LIST="${IPS_LIST}RECOMMENDED:${RECOMMENDED_IP}, Other"
                db_subst opensand-daemon/interconnect/interface_ip_preset ips_list ${IPS_LIST}
                db_set opensand-daemon/interconnect/interface_ip_preset "Current:${CURRENT_IP}"
                db_input low opensand-daemon/interconnect/interface_ip_preset || true
            fi
            db_endblock
        ;;
        6)
            db_beginblock
            if [ "$NAME" = "GW-PHY" -o "$NAME" = "GW-NET-ACC" ]; then
                db_get opensand-daemon/interconnect/interface_ip_preset
                if [ "${RET}" = "Other" ]; then
                    db_set opensand-daemon/interconnect/interface_ip "${RECOMMENDED_IP}"
                    db_input high opensand-daemon/interconnect/interface_ip || true
                elif [[ $RET == Current* ]]; then
                    db_set opensand-daemon/interconnect/interface_ip ${CURRENT_IP}
                else
                    db_set opensand-daemon/interconnect/interface_ip ${RECOMMENDED_IP}
                fi
            fi
            db_endblock
        ;;
        7)
            db_beginblock
            if [ "$NAME" = "GW-PHY" ]; then
                db_subst opensand-daemon/interconnect/ip_remote ip_remote_desc "GW-NET-ACC"
                db_input low opensand-daemon/interconnect/ip_remote || true
            fi
            db_endblock
        ;;
        8)
            db_beginblock
            if [ "$NAME" = "GW-PHY" -o "$NAME" = "GW-NET-ACC" ]; then
                db_subst opensand-daemon/interconnect/port_upward port_upward_bottom "GW-PHY"
                db_subst opensand-daemon/interconnect/port_upward port_upward_top "GW-NET-ACC"
                db_input low opensand-daemon/interconnect/port_upward || true
            fi
            db_endblock
        ;;
        9)
            db_beginblock
            if [ "$NAME" = "GW-PHY" -o "$NAME" = "GW-NET-ACC" ]; then
                db_subst opensand-daemon/interconnect/port_downward port_downward_bottom "GW-PHY"
                db_subst opensand-daemon/interconnect/port_downward port_downward_top "GW-NET-ACC"
                db_input low opensand-daemon/interconnect/port_downward || true
            fi
            db_endblock
        ;;
        10)
            db_beginblock
            if [ "$NAME" = "ST" ]; then
                db_subst opensand-daemon/service/st_instance inst_list ${ST_LIST}
                db_subst opensand-daemon/service/st_instance inst_description ${ST_INST_DESCR}
                db_input high opensand-daemon/service/st_instance || true
            fi
            if [ "$NAME" = "GW" -o "$NAME" = "GW-PHY" -o "$NAME" = "GW-NET-ACC" ]; then
                db_subst opensand-daemon/service/st_instance inst_list ${GW_LIST}
                db_subst opensand-daemon/service/st_instance inst_description ${GW_INST_DESCR}
                db_input high opensand-daemon/service/st_instance || true
            fi
            if [ "$NAME" = "WS" ]; then
                # enable WS2
                db_subst opensand-daemon/service/st_instance inst_list ${WS_LIST}
                db_input high opensand-daemon/service/st_instance || true
            fi
        ;;
        11)
            if [ "$NAME" = "ST" ]; then
                db_get opensand-daemon/service/st_instance
                INST=$RET
            fi
            if [ "$NAME" = "GW" -o "$NAME" = "GW-PHY" -o "$NAME" = "GW-NET-ACC" ]; then
                db_get opensand-daemon/service/st_instance
                INST=$RET
            fi
            if [ "$NAME" = "WS" ]; then
                db_get opensand-daemon/service/st_instance
                INST=$RET
                db_input high opensand-daemon/service/ws_instance || true
            fi
        ;;
        12)
            db_subst opensand-daemon/service/interface ifaces_list "all, ${IFACES_LIST}"
            db_input high opensand-daemon/service/interface || true
            db_endblock
        ;;
        13)
            db_beginblock
            db_get opensand-daemon/service/interface
            if [ "$RET" = "all" ]; then
                db_reset opensand-daemon/service/interface
                db_set opensand-daemon/service/interface ""
            fi
            db_input low opensand-daemon/service/port || true
            db_endblock
        ;;
        14)
            db_beginblock
            db_input low opensand-daemon/command/port || true
            db_endblock
        ;;
        15)
            db_beginblock
            db_input low opensand-daemon/state/port || true
            db_endblock
        ;;
        16)
            db_beginblock
            db_input high opensand-daemon/network/config_level || true
        ;;
        17)
            db_get opensand-daemon/network/config_level
            CONFIG_LEVEL=$RET
            if [ "$NAME" != "SAT" -a "$NAME" != "GW-PHY" ]; then
                db_input high opensand-daemon/network/dhcp || true
            fi
        ;;
        18)
            if [ "$NAME" != "SAT" -a "$NAME" != "GW-PHY" ]; then
                db_get opensand-daemon/network/dhcp
                DHCP=$RET
                if [ "$NAME" != "WS" -a "$DHCP" = "true" ]; then
                    db_input high opensand-daemon/network/default_route || true
                fi
            fi
        ;;
        19)
            db_beginblock
            if [ "$NAME" != "WS"  -a "$NAME" != "GW-NET-ACC" ]; then
                db_subst opensand-daemon/network/emu_iface ifaces_list "${IFACES_LIST}"
                db_input high opensand-daemon/network/emu_iface || true
            fi
            db_endblock
        ;;
        20)
            db_beginblock
            if [ "$CONFIG_LEVEL" != "AUTOMATIC" ]; then
                if [ "$NAME" != "WS"  -a "$NAME" != "GW-NET-ACC" ]; then
                    db_get opensand-daemon/network/emu_iface
                    EMU_IFACE=${RET}
                    if [ "$NAME" = "SAT" ]; then
                        RECOMMENDED_IP=${SAT_EMU_IP4ADDR}
                    elif [ "$NAME" = "GW" -o "$NAME" = "GW-PHY" ]; then
                        if [ "${INST}" = "0" ]; then 
                            RECOMMENDED_IP=${GW_EMU_IP4ADDR}
                        else
                            RECOMMENDED_IP="192.168.18.${INST}/24"
                        fi
                    elif [ "$NAME" = "ST" ]; then
                        RECOMMENDED_IP="192.168.18.${INST}/24"
                    fi
                    # Prepare list: current, recommended, other
                    IPS_LIST=""
                    db_get opensand-daemon/network/emu_ipv4
                    CURRENT_IP=${RET}
                    if [ ! -z $CURRENT_IP ]; then
                        IPS_LIST="Current:${CURRENT_IP}, "
                    fi
                    IPS_LIST="${IPS_LIST}RECOMMENDED:${RECOMMENDED_IP}, Other"
                    db_subst opensand-daemon/network/emu_ipv4_preset ips_list "${IPS_LIST}"
                    db_set opensand-daemon/network/emu_ipv4_preset "Current:${CURRENT_IP}"
                    db_input high opensand-daemon/network/emu_ipv4_preset || true
                fi
            fi
            db_endblock
        ;;
        21)
            db_beginblock
            if [ "$CONFIG_LEVEL" != "AUTOMATIC" ]; then
                if [ "$NAME" != "WS"  -a "$NAME" != "GW-NET-ACC" ]; then
                    db_get opensand-daemon/network/emu_ipv4_preset
                    if [ "${RET}" = "Other" ]; then
                        db_set opensand-daemon/network/emu_ipv4 "${RECOMMENDED_IP}"
                        db_input high opensand-daemon/network/emu_ipv4 || true
                    elif [[ $RET == Current* ]]; then
                        db_set opensand-daemon/network/emu_ipv4 ${CURRENT_IP}
                    else
                        db_set opensand-daemon/network/emu_ipv4 ${RECOMMENDED_IP}
                    fi
                fi
            fi
            db_endblock
        ;;
        22)
            db_beginblock
            if [ "$CONFIG_LEVEL" != "AUTOMATIC" ]; then
                if [ "$NAME" != "SAT" -a "$NAME" != "GW-PHY" ]; then
                    add=1
                    if [ "$NAME" = "WS" ]; then
                        db_subst opensand-daemon/network/ws_lan_iface ifaces_list "${IFACES_LIST}"
                        db_input high opensand-daemon/network/ws_lan_iface || true
                        # use a random value to limit WS with the same address
                        # ST physical interface has address .1 and tun interface
                        # (opensand) has address .3
                        add=`od -An -N1 -tu1 /dev/urandom`
                        add=$((add % 252))
                        add=$((add + 4))
                    else
                        db_subst opensand-daemon/network/lan_iface ifaces_list "${IFACES_LIST}"
                        db_input high opensand-daemon/network/lan_iface || true
                    fi
                fi
            else
                if [ "$NAME" != "SAT" -a "$NAME" != "GW-PHY" ] && 
                    [ "$NAME" != "WS" -o "$DHCP" != "false" ]; then
                    if [ "$NAME" = "WS" ]; then
                        db_subst opensand-daemon/network/ws_lan_iface ifaces_list "${IFACES_LIST}"
                        db_input high opensand-daemon/network/ws_lan_iface || true
                    else
                        db_subst opensand-daemon/network/lan_iface ifaces_list "${IFACES_LIST}"
                        db_input high opensand-daemon/network/lan_iface || true
                    fi
                fi
            fi
            db_endblock
        ;;
        23)
            db_beginblock
            if [ "$CONFIG_LEVEL" != "AUTOMATIC" ]; then
                if [ "$NAME" != "SAT" -a "$NAME" != "GW-PHY" ]; then
                    if [ "$NAME" = "WS" ]; then
                        db_get opensand-daemon/network/ws_lan_iface
                    else
                        db_get opensand-daemon/network/lan_iface
                    fi
                    LAN_IFACE=${RET}
                    if [ "$NAME" != "WS" -o "$DHCP" = "false" ]; then
                        if [ "$NAME" != "GW" -a "$NAME" != "GW-NET-ACC" ]; then
                            net=$((18+$INST))
                            # WS behind GW
                            if [ "$INST" = "0" ]; then
                                net="$GW_NET"
                            fi
                            if [ "$NAME" = "WS" ]; then
                                RECOMMENDED_IP="192.168.${net}.${add}/24"
                            else
                                RECOMMENDED_IP="192.168.${net}.${add}/24"
                            fi
                            net=$((101+$INST))
                            # WS behind GW0
                            if [ "$INST" = "0" ]; then
                                net="1$GW_NET"
                            fi
                        else
                            if [ "${INST}" = "0" ]; then 
                                RECOMMENDED_IP=${GW_IP4ADDR}
                            else
                                net=$((18+$INST))
                                RECOMMENDED_IP="192.168.${net}.${add}/24"
                            fi
                        fi
                        # Prepare list: current, recommended, other
                        IPS_LIST=""
                        if [ "$NAME" = "WS" ]; then
                            db_get opensand-daemon/network/ws_lan_ipv4
                        else
                             db_get opensand-daemon/network/lan_ipv4
                        fi
                        CURRENT_IP=${RET}
                        if [ ! -z $CURRENT_IP ]; then
                            IPS_LIST="Current:${CURRENT_IP}, "
                        fi
                        IPS_LIST="${IPS_LIST}RECOMMENDED:${RECOMMENDED_IP}, Other"
                        if [ "$NAME" = "WS" ]; then
                            db_subst opensand-daemon/network/ws_lan_ipv4_preset ips_list "${IPS_LIST}"
                            db_set opensand-daemon/network/ws_lan_ipv4_preset "Current:${CURRENT_IP}"
                            db_input high opensand-daemon/network/ws_lan_ipv4_preset || true
                        else
                            db_subst opensand-daemon/network/lan_ipv4_preset ips_list "${IPS_LIST}"
                            db_set opensand-daemon/network/lan_ipv4_preset "Current:${CURRENT_IP}"
                            db_input high opensand-daemon/network/lan_ipv4_preset || true
                        fi
                    fi
                fi
            fi
            db_endblock
        ;;
        24)
            db_beginblock
            if [ "$CONFIG_LEVEL" != "AUTOMATIC" ]; then
                if [ "$NAME" != "SAT" -a "$NAME" != "GW-PHY" ]; then
                    if [ "$NAME" != "WS" -o "$DHCP" = "false" ]; then
                        if [ "$NAME" = "WS" ]; then
                            db_get opensand-daemon/network/ws_lan_ipv4_preset
                            if [ "${RET}" = "Other" ]; then
                                db_subst opensand-daemon/network/ws_lan_ipv4 recommended_ip "${RECOMMENDED_IP}"
                                db_input high opensand-daemon/network/ws_lan_ipv4 || true
                            elif [[ $RET == Current* ]]; then
                                db_set opensand-daemon/network/ws_lan_ipv4 ${CURRENT_IP}
                            else
                                db_set opensand-daemon/network/ws_lan_ipv4 ${RECOMMENDED_IP}
                            fi
                        else
                            db_get opensand-daemon/network/lan_ipv4_preset
                            if [ "${RET}" = "Other" ]; then
                                db_set opensand-daemon/network/lan_ipv4 "${RECOMMENDED_IP}"
                                db_input high opensand-daemon/network/lan_ipv4 || true
                            elif [[ $RET == Current* ]]; then
                                db_set opensand-daemon/network/lan_ipv4 ${CURRENT_IP}
                            else
                                db_set opensand-daemon/network/lan_ipv4 ${RECOMMENDED_IP}
                            fi
                        fi
                    fi
                fi
            fi
            db_endblock
        ;;
        25)
            db_beginblock
            if [ "$CONFIG_LEVEL" != "AUTOMATIC" ]; then
                if [ "$NAME" != "SAT" -a "$NAME" != "GW-PHY" ]; then
                    if [ "$NAME" != "WS" -o "$DHCP" = "false" ]; then
                        if [ "$NAME" != "GW" -a "$NAME" != "GW-NET-ACC" ]; then
                            net=$((18+$INST))
                            # WS behind GW
                            if [ "$INST" = "0" ]; then
                                net="$GW_NET"
                            fi
                            net=$((101+$INST))
                            # WS behind GW0
                            if [ "$INST" = "0" ]; then
                                net="1$GW_NET"
                            fi
                            if [ "$NAME" = "WS" ]; then
                                RECOMMENDED_IP="2001:660:6602:${net}::${add}/64"
                            else
                                RECOMMENDED_IP="2001:660:6602:${net}::${add}/64"
                            fi
                        else
                            if [ "${INST}" = "0" ]; then 
                                RECOMMENDED_IP=${GW_IP6ADDR}
                            else
                                net=$((101+$INST))
                                RECOMMENDED_IP="2001:660:6602:${net}::${add}/64"
                            fi
                        fi
                        # Prepare list: current, recommended, other
                        IPS_LIST=""
                        if [ "$NAME" = "WS" ]; then
                            db_get opensand-daemon/network/ws_lan_ipv6
                        else
                            db_get opensand-daemon/network/lan_ipv6
                        fi
                        CURRENT_IP=${RET}
                        if [ ! -z $CURRENT_IP ]; then
                            IPS_LIST="Current:${CURRENT_IP}, "
                        fi
                        IPS_LIST="${IPS_LIST}RECOMMENDED:${RECOMMENDED_IP}, Other"
                        if [ "$NAME" = "WS" ]; then
                            db_subst opensand-daemon/network/ws_lan_ipv6_preset ips_list "${IPS_LIST}"
                            db_set opensand-daemon/network/ws_lan_ipv6_preset "Current:${CURRENT_IP}"
                            db_input high opensand-daemon/network/ws_lan_ipv6_preset || true
                        else
                            db_subst opensand-daemon/network/lan_ipv6_preset ips_list "${IPS_LIST}"
                            db_set opensand-daemon/network/lan_ipv6_preset "Current:${CURRENT_IP}"
                            db_input high opensand-daemon/network/lan_ipv6_preset || true
                        fi
                    elif [ "$NAME" = "WS" -a "$DHCP" != "false" ]; then
                        net=$((101+$INST))
                        # WS behind GW
                        if [ "$INST" = "0" ]; then
                            net="1$GW_NET"
                        fi
                        RECOMMENDED_IP="2001:660:6602:${net}::${add}/64"
                        IPS_LIST=""
                        db_get opensand-daemon/network/ws_lan_ipv6
                        CURRENT_IP=${RET}
                        if [ ! -z $CURRENT_IP ]; then
                            IPS_LIST="CURRENT: ${CURRENT_IP}, "
                        fi
                        IPS_LIST="${IPS_LIST}RECOMMENDED:${RECOMMENDED_IP}, OTHER"
                        db_subst opensand-daemon/network/ws_lan_ipv6_preset ips_list "${IPS_LIST}"
                        db_set opensand-daemon/network/ws_lan_ipv6_preset "Current:${CURRENT_IP}"
                        db_input high opensand-daemon/network/ws_lan_ipv6_preset || true
                    fi
                fi
            fi
            db_endblock
        ;;
        26)
            db_beginblock
            if [ "$CONFIG_LEVEL" != "AUTOMATIC" ]; then
                if [ "$NAME" != "SAT" -a "$NAME" != "GW-PHY" ]; then
                    if [ "$NAME" != "WS" -o "$DHCP" = "false" ]; then
                        if [ "$NAME" = "WS" ]; then
                            db_get opensand-daemon/network/ws_lan_ipv6_preset
                            if [ "${RET}" = "Other" ]; then
                                db_subst opensand-daemon/network/ws_lan_ipv6 recommended_ip "${RECOMMENDED_IP}"
                                db_input high opensand-daemon/network/ws_lan_ipv6 || true
                            elif [[ $RET == Current* ]]; then
                                db_set opensand-daemon/network/ws_lan_ipv6 ${CURRENT_IP}
                            else
                                db_set opensand-daemon/network/ws_lan_ipv6 ${RECOMMENDED_IP}
                            fi
                        else
                            db_get opensand-daemon/network/lan_ipv6_preset
                            if [ "${RET}" = "Other" ]; then
                                db_subst opensand-daemon/network/lan_ipv6 recommended_ip "${RECOMMENDED_IP}"
                                db_input high opensand-daemon/network/lan_ipv6 || true
                            elif [[ $RET == Current* ]]; then
                                db_set opensand-daemon/network/lan_ipv6 ${CURRENT_IP}
                            else
                                db_set opensand-daemon/network/lan_ipv6 ${RECOMMENDED_IP}
                            fi
                        fi
                    elif [ "$NAME" = "WS" -a "$DHCP" != "false" ]; then
                        db_get opensand-daemon/network/ws_lan_ipv6_preset
                        if [ "${RET}" = "Other" ]; then
                            db_subst opensand-daemon/network/ws_lan_ipv6 recommended_ip "${RECOMMENDED_IP}"
                            db_input high opensand-daemon/network/ws_lan_ipv6 || true
                        elif [[ $RET == Current* ]]; then
                            db_set opensand-daemon/network/ws_lan_ipv6 ${CURRENT_IP}
                        else
                            db_set opensand-daemon/network/ws_lan_ipv6 ${RECOMMENDED_IP}
                        fi
                    fi
                fi
            fi
            db_endblock
        ;;
        *)
            # The default case catches when $STATE is greater than the
            # last implemented state, and breaks out of the loop. This
            # requires that states be numbered consecutively from 1
            # with no gaps, as the default case will also be entered
            # if there is a break in the numbering
            break # exits the enclosing "while" loop
        ;;
        esac

        if db_go; then
            STATE=$(($STATE + 1))
        else
            STATE=$(($STATE - 1))
        fi
    done

    if [ $STATE -eq 0 ]; then
        # The user has asked to back up from the first
        # question. This case is problematical. Regular
        # dpkg and apt package installation isn’t capable
        # of backing up questions between packages as this
        # is written, so this will exit leaving the package
        # unconfigured - probably the best way to handle
        # the situation.
        exit 10
    fi
}

reset(){
    db_reset opensand-daemon/service/name
    db_reset opensand-daemon/service/name_adv
    db_reset opensand-daemon/service/type
    db_reset opensand-daemon/service/st_instance
    db_reset opensand-daemon/service/ws_instance
    db_reset opensand-daemon/service/interface
    db_reset opensand-daemon/service/port
    db_reset opensand-daemon/command/port
    db_reset opensand-daemon/state/port
    db_reset opensand-daemon/network/config_level
    db_reset opensand-daemon/network/dhcp
    db_reset opensand-daemon/network/default_route
    db_reset opensand-daemon/network/emu_iface
    db_reset opensand-daemon/network/emu_ipv4
    db_reset opensand-daemon/network/emu_ipv4_preset
    db_reset opensand-daemon/network/lan_iface
    db_reset opensand-daemon/network/lan_ipv4
    db_reset opensand-daemon/network/lan_ipv4_preset
    db_reset opensand-daemon/network/lan_ipv6
    db_reset opensand-daemon/network/lan_ipv6_preset
    db_reset opensand-daemon/network/ws_lan_iface
    db_reset opensand-daemon/network/ws_lan_ipv4
    db_reset opensand-daemon/network/ws_lan_ipv4_preset
    db_reset opensand-daemon/network/ws_lan_ipv6
    db_reset opensand-daemon/network/ws_lan_ipv6_preset
    db_reset opensand-daemon/interconnect/ip_remote
    db_reset opensand-daemon/interconnect/interface
    db_reset opensand-daemon/interconnect/interface_ip
    db_reset opensand-daemon/interconnect/interface_ip_preset
    db_reset opensand-daemon/interconnect/port_upward
    db_reset opensand-daemon/interconnect/port_downward
}

unseen(){
    db_fset opensand-daemon/service/name seen false
    db_fset opensand-daemon/service/name_adv seen false
    db_fset opensand-daemon/service/type seen false
    db_fset opensand-daemon/service/st_instance seen false
    db_fset opensand-daemon/service/ws_instance seen false
    db_fset opensand-daemon/service/interface seen false
    db_fset opensand-daemon/service/port seen false
    db_fset opensand-daemon/command/port seen false
    db_fset opensand-daemon/state/port seen false
    db_fset opensand-daemon/network/config_level seen false
    db_fset opensand-daemon/network/dhcp seen false
    db_fset opensand-daemon/network/default_route seen false
    db_fset opensand-daemon/network/emu_iface seen false
    db_fset opensand-daemon/network/emu_ipv4 seen false
    db_fset opensand-daemon/network/emu_ipv4_preset seen false
    db_fset opensand-daemon/network/lan_iface seen false
    db_fset opensand-daemon/network/lan_ipv4 seen false
    db_fset opensand-daemon/network/lan_ipv4_preset seen false
    db_fset opensand-daemon/network/lan_ipv6 seen false
    db_fset opensand-daemon/network/lan_ipv6_preset seen false
    db_fset opensand-daemon/network/ws_lan_iface seen false
    db_fset opensand-daemon/network/ws_lan_ipv4 seen false
    db_fset opensand-daemon/network/ws_lan_ipv4_preset seen false
    db_fset opensand-daemon/network/ws_lan_ipv6 seen false
    db_fset opensand-daemon/network/ws_lan_ipv6_preset seen false
    db_fset opensand-daemon/interconnect/ip_remote seen false
    db_fset opensand-daemon/interconnect/interface seen false
    db_fset opensand-daemon/interconnect/interface_ip_preset seen false
    db_fset opensand-daemon/interconnect/interface_ip seen false
    db_fset opensand-daemon/interconnect/port_upward seen false
    db_fset opensand-daemon/interconnect/port_downward seen false
}

db_capb backup

if [ "$#" -gt 0 ]; then
    if [ "$1" = "configure" ]; then
        db_fget opensand-daemon/default seen
        if [ "$RET" = "false" ]; then
            db_input high opensand-daemon/default || true
            db_get opensand-daemon/default
            if [ "$RET" = "true" ]; then
                reset
                db_stop
            else
                configure
            fi
        else
            configure
        fi
    elif [ "$1" = "reconfigure" ]; then
        unseen
        configure
    else
        usage
        exit 1
    fi
else
    usage
fi

exit 0
