#!/bin/sh

# script to bring up the tun devices in QEMU in bridged mode 
# for OpenSand Live
#
# some constants specific to the local host
#

BR0IP=192.168.18.15
GATEWAY=192.168.18.15
BROADCAST=192.168.18.255

#
# Bring up the tap device (name specified as first argument, by QEMU)
#

tunctl -u `id -un` -t tap_gw
tunctl -u `id -un` -t tap_st1

ip link set tap_gw up
ip link set tap_st1 up

#
# create the bridge between the tap devices
#

/usr/sbin/brctl addbr br_opensand
/usr/sbin/brctl addif br_opensand tap_gw
/usr/sbin/brctl addif br_opensand tap_st1

# 
# only a single bridge so loops are not possible, turn off spanning tree protocol
#

/usr/sbin/brctl stp br_opensand off 

# 
# Bring up the bridge with BR0IP 
#

/sbin/ifconfig br_opensand $BR0IP netmask 255.255.255.0 broadcast $BROADCAST

