#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule


usage(){
    /bin/echo -e "Usage: $0 command\n\twith command: configure or reconfigure"
}

configure(){
    STATE=1
    while true; do
        case "$STATE" in
        1)
            db_beginblock
            db_input high opensand-manager/collector/exists || true
            db_get opensand-manager/collector/exists
            HAS_COLLECTOR=${RET}
            db_endblock
        ;;
        2)
            db_beginblock
            if [ "${HAS_COLLECTOR}" = "true" ]; then
                db_input high opensand-manager/collector/ip || true
            fi
        ;;
        3)
            if [ "${HAS_COLLECTOR}" = "true" ]; then
                db_input low opensand-manager/collector/stats/port || true
            fi
        ;;
        4)
            if [ "${HAS_COLLECTOR}" = "true" ]; then
                db_input low opensand-manager/collector/logs/port || true
            fi
            db_endblock
        ;;
        *)
            # The default case catches when $STATE is greater than the
            # last implemented state, and breaks out of the loop. This
            # requires that states be numbered consecutively from 1
            # with no gaps, as the default case will also be entered
            # if there is a break in the numbering
            break # exits the enclosing "while" loop
        ;;
        esac

        if db_go; then
            STATE=$(($STATE + 1))
        else
            STATE=$(($STATE - 1))
        fi
    done

    if [ $STATE -eq 0 ]; then
        # The user has asked to back up from the first
        # question. This case is problematical. Regular
        # dpkg and apt package installation isn’t capable
        # of backing up questions between packages as this
        # is written, so this will exit leaving the package
        # unconfigured - probably the best way to handle
        # the situation.
        exit 10
    fi
}

unseen(){
    db_fset opensand-manager/collector/ip seen false
    db_fset opensand-manager/collector/stats/port seen false
    db_fset opensand-manager/collector/logs/port seen false
}

db_capb backup

if [ "$#" -gt 0 ]; then
    if [ "$1" = "configure" ]; then
        configure
    elif [ "$1" = "reconfigure" ]; then
        unseen
        configure
    else
        usage
        exit 1
    fi
else
    usage
fi

exit 0
